---
- hosts: localhost
  gather_facts: no

  vars:

  - brew_taps:
      - homebrew/dupes       # These formulae duplicate software provided by OS X, though may provide more recent or bugfix versions
      - homebrew/core        # Tap for core
      - homebrew/services    # Tap for services
      - homebrew/versions    # These formulae provide multiple versions of existing packages
      - homebrew/completions # Shell completion formulae
      - homebrew/nginx       # Tap for Nginx
      - homebrew/php         # Tap for php
      - homebrew/bundle      # Tap for bundle
      - caskroom/cask        # Homebrew Cask extends Homebrew and brings its elegance, simplicity, and speed to OS X applications and large binaries alike.
      - caskroom/versions    # alternate versions of Casks
      - JFrogDev/tap         # Tap for JFrog
      - neovim/neovim        # Tap for NeoVim

  - brew_install:
      - coreutils   # GNU File, Shell, and Text utilities
      - ack         # Search tool like grep, but optimized for programmers
      - bash        # Bash (Bourne-again SHell) is a UNIX command interpreter
      - diffutils   # Package of several programs related to finding differences between files
      - gawk        # GNU awk utility
      - git         # Distributed revision control system
      - gzip        # Popular GNU data compression program
      - less        # Less is a free, open-source file pager
      - rsync       # Utility that provides fast incremental file transfer
      - ssh-copy-id # Add a public key to a remote machine's authorized_keys file
      - tree        # Display directories as trees (with optional color/HTML output)
      - vim         # Vi "workalike" with many additional features
      - wdiff       # Display word differences between text files
      - wget        # Internet file retriever
      - stormssh    # Command-line tool to manage your ssh connections
      - htop        # Improved top (interactive process viewer) for OS X
      - pkgdiff     # Tool for analyzing changes in software packages
      - the_platinum_searcher #  Multi-platform code-search similar to ack and ag
      - neovim      #  Ambitious Vim-fork focused on extensibility and agility
      - shellcheck  # Static analysis and lint tool, for (ba)sh scripts
      - ansifilter  # Strip or convert ANSI codes into HTML, (La)Tex, RTF, or BBCode
      - jq          # JSON Processor
      - ripgrep     # Search tool like grep and The Silver Searcher.

  - brew_install_with_default_names:
      - findutils   # Collection of GNU find, xargs, and locate
      - gnu-sed     # GNU implementation of the famous stream editor
      - gnu-tar     # GNU version of the tar archiving utility
      - gnu-which   # GNU implementation of which utility
      - grep        # GNU grep utility

  - brew_cask_install:
      - java          # Java Standard Edition Development Kit
      - iterm2        # iTerm2 is a GPL-licensed terminal emulator for OS X.
      - sublime-text # Sublime Text is a sophisticated text editor for code, markup and prose.
      - atom          # https://atom.io/
      - nvalt         # http://brettterpstra.com/project/nvalt/

  tasks:
    - name: install homebrew taps
      homebrew_tap:
        tap: "{{ item }}"
        state: present
      with_items: "{{ brew_taps }}"

    - name: update homebrew and packages
      homebrew: update_homebrew=yes upgrade_all=yes

    - name: installing tools using homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      with_items: "{{ brew_install }}"
      ignore_errors: yes

    - name: installing tools using homebrew with default names
      homebrew:
        name: "{{ item }}"
        state: present
        install_options: with-default-names
      with_items: "{{ brew_install_with_default_names }}"

    - name: installing tools using homebrew cask
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items: "{{ brew_cask_install }}"

    - name: installing ci tools
      homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - jenkins            # Extendable open source continuous integration server
        - sonar              # Manage code quality
        - sonar-scanner      # Launcher to analyze a project with SonarQube
        - sonarlint          # provides pre-commit feedback on quality issues injected into code.
        - artifactory        # Binary Repository Manager from JFrog
