---
- hosts: localhost
  gather_facts: no
  tasks:

  - name: installing comparison tools
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - araxis-merge     # http://www.araxis.com/merge
      - beyond-compare   # beyond-compare
      - kaleidoscope     # http://www.kaleidoscopeapp.com/
      - deltawalker      # DeltaWalker
      - p4merge          # Perforce P4Merge
      - diffmerge        # DiffMerge
      - changes          # Changes
      - kdiff3           # File comparison tool
