---
- hosts: localhost
  gather_facts: no
  tasks:

  - name: installing mysql using homebrew
    homebrew:
      name: "{{ item }}"
      state: present
    with_items:
      - mysql            # Java-based project management

  - name: installing mysql IDE's tools using homebrew cask
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - sequel-pro       # fast, easy-to-use Mac database management application for working with MySQL databases
