---
- hosts: localhost
  gather_facts: yes
  tasks:

  - name: clone repofactor
    git:
      repo: https://github.com/bloomberg/repofactor.git
      dest: ~/bin/repofactor
      clone: yes
      depth:  1

  - name: add repofactor to PATH
    lineinfile:
      dest: "{{ ansible_env.HOME }}/.zshrc"
      state: present
      regexp: '^export PATH='
      line: "export PATH=$PATH:${HOME}/bin/repofactor"


