---
- hosts: localhost
  gather_facts: no
  tasks:

    - name: installing zsh
      homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - zsh             # UNIX shell (command interpreter)
        - zsh-lovers      # Tips, tricks, and examples for zsh
        - z               # Tracks most-used directories to make cd smarter # Jump Around - https://github.com/rupa/z
        - v               # Z for vim
        - zsh-completions  # Additional completion definitions for zsh
        - zsh-syntax-highlighting  # Fish shell like syntax highlighting for zsh
        - zsh-history-substring-search # Zsh port of Fish shell's history search
        - zsh-autosuggestions  # Fish-like fast/unobtrusive autosuggestions for zsh
        - zsh-git-prompt   # Informative git prompt for zsh

    - name: installing oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    - name: configuring zsh plugins
      lineinfile:
        dest: ~/.zshrc
        regexp: ^plugins=
        line: "plugins=(git mvn brew docker scala svn bundler osx rake ruby zsh_reload sudo extract z sudo sublime)"

    - name: configuring zsh-completions
      lineinfile:
        dest: ~/.zshrc
        line: "fpath=(/usr/local/share/zsh-completions $fpath)"

    - name: configuring zsh-syntax-highlighting
      lineinfile:
        dest: ~/.zshrc
        line: "source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

    - name: configuring zsh-syntax-highlighting-search
      lineinfile:
        dest: ~/.zshrc
        line: "source /usr/local/opt/zsh-history-substring-search/zsh-history-substring-search.zsh"

    - name: configuring zsh-autosuggestions
      lineinfile:
        dest: ~/.zshrc
        line: "source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh"


    - name: .z
      shell: if [ ! -f "~/.z" ]; then touch  "$HOME/.z"; fi

    - name: disabling homebrew analytics zshrc
      lineinfile:
        dest: ~/.zshrc
        line: "export HOMEBREW_NO_ANALYTICS=1"
      tags: analytics


    - name: configuring z in zsh
      lineinfile:
        dest: ~/.zshrc
        line: " . `brew --prefix`/etc/profile.d/z.sh"

    - name: change zsh theme to pygmalion
      replace:
        dest: ~/.zshrc
        regexp: 'robbyrussell'
        replace: 'pygmalion'
        backup: no
